Services integration 3
roc-streaming/roc-droid pull request #123
Opened 2024-10-25 16:16 UTC by Izchomatik

2024-12-18 09:54 UTC, gavv reviewed
Thanks!

2024-12-18 09:54 UTC, gavv commented on lib/src/ui/components/roc_button.dart
> +      required Future<void> Function() activeFunction,
Nit: maybe name like activatedFunction / deactivatedFunction would be more intuitive (it'd suggest that they are called on event).

2024-12-18 09:54 UTC, gavv commented on lib/src/agent/android_backend.dart
> +  final Event<Value<String>> stateChangeEvent = Event("stateChangeEvent");
It's preferably to use enums instead of string identifiers. If you change a string in one place, but forget to change it in another, you won't get a compiler error and the change will remain unnoticed.

We could introduce `BackendEvent` enum and use `Event<Value<BackendEvent>>`. Alternatively, we can create two separate events without values at all: `senderStateChangeEvent` and `receiverStateChangeEvent`.

2024-12-18 09:54 UTC, gavv commented on lib/src/agent/android_backend.dart
> +  bool senderIsAlive = false;
Since receiverIsAlive/senderIsAlive values are now cached until onAnyEvents is called, it can lead to a small inconsistency: model calls startReceiver() and then reads receiverIsAlive and it can see that it's false just because event was not delivered from kotlin to dart yet.

To avoid this, we can update startReceiver/stopReceiver/startSender/stopSender so that they will update receiverIsAlive/senderIsAlive before returning.

2024-12-18 09:54 UTC, gavv commented on lib/src/model/model_root.dart
> +    this.receiver.setDefultValues();
Maybe inline setDefultValues logic into ctor? Isn't it an implementation detail?

2024-12-18 09:54 UTC, gavv commented on lib/src/model/receiver.dart
It seems that we can remove setReceiverIPs() method. UI doesn't need to set write this field, only read it.

2025-01-17 21:49 UTC, Izchomatik commented on lib/src/model/receiver.dart
Method removed

2025-01-17 21:49 UTC, Izchomatik commented on lib/src/model/model_root.dart
> +    this.receiver.setDefultValues();
Moved to constructor

2025-01-17 21:50 UTC, Izchomatik commented on lib/src/agent/android_backend.dart
> +  bool senderIsAlive = false;
Added try/finally clauses

2025-01-17 21:50 UTC, Izchomatik commented on lib/src/agent/android_backend.dart
> +  final Event<Value<String>> stateChangeEvent = Event("stateChangeEvent");
Added `BackendEvent` enum

2025-01-17 21:52 UTC, Izchomatik commented on lib/src/ui/components/roc_button.dart
> +      required Future<void> Function() activeFunction,
Renamed

2025-01-21 12:38 UTC, gavv commented on lib/src/agent/android_backend.dart
> +  final Event<Value<String>> stateChangeEvent = Event("stateChangeEvent");
So currently we have this:

``` dart
enum BackendEvent {
  stateChangeEvent,
  statusCheckEvent,
  failureEvent,
}

...

final Event<Value<String>> stateChangeEvent =
    Event(BackendEvent.stateChangeEvent.name);

...

void onEvent(AndroidServiceEvent eventCode) async {
  await refreshState(eventCode.name);
  stateChangeEvent.broadcast(Value(eventCode.name));
}
```

This is odd:

- `BackendEvent` enum is not actually used as enum. We get a string name of its member and use this string as the name of `Event` object. This string is not even passed to subscribers. It's just define the name of the object for debugging, logging, etc.

- When model subscribes to events, it still get string event identifiers because we use `Event<Value<String>>`. Those strings are not related to `BackendEvent` enum - they're string names of `AndroidServiceEvent` enum values which we pass to subscribers in onEvent().

What I was talking about is to avoid broadcasting strings from backend to subscribers, and instead broadcast enum values. 

As for the name argument of `Event` object, we may set it, but not necessarily, this doesn't really matter.

2025-01-21 16:45 UTC, gavv commented on lib/src/agent/android_backend.dart
> +  final Event<Value<String>> stateChangeEvent = Event("stateChangeEvent");
BTW, for `failureEvent` I think it's not necessary to change string to enum. Instead, we could keep string, but send human-readable error text instead of stringified error code. E.g. if the code was `AndroidServiceError.senderConnectFailed`, we can send "Failed to connect sender to remote peer", and so on.

2025-01-21 17:14 UTC, gavv commented on lib/src/agent/android_backend.dart
> +  bool senderIsAlive = false;
I just realized there is another minor problem remaining.

Suppose we call, say, `startReceiver()`, which in turn calls `refreshState()`, and alive status is updated. However, for some reason, backend fails to generate event (e.g. service was restarting at this moment or something like that).

This would lead to another inconsistency: we've reported new state, but we haven't generated event to updated all parts of code according to the new state.

It's not quite clear if this situation is possible, but this class (`AndroidBackend`) is a boundary between two domains (kotlin and flutter), hence I think it makes sense to have some safety measures here.

We could rework event generation to be more robust, so that state changes and events are guaranteed to be consistent. Something like this:

```dart
Future<void> startReceiver(AndroidReceiverSettings settings) async {
  ...
  } finally {
    await refreshState();
  }
}

...
    
void onEvent(AndroidServiceEvent eventCode) async {
  _logger.d("Registered event: $eventCode");
  await refreshState();
  // note: no broadcast here
}

...

Future<void> refreshState(String eventCode) async {
  final newReceiverIsAlive = await _connector.isReceiverAlive();
  if (receiverIsAlive != newReceiverIsAlive) {
    _logger.d("Detected receiver state change from $receiverIsAlive to $newReceiverIsAlive");
    receiverIsAlive = newReceiverIsAlive;
    // note: call to broadcast() is now here
    // whenever state changes, no matter how we've found out (from kotlin
    // event of from finally block), we notify subscribers
    stateChangeEvent.broadcast(Value(BackendEvent.receiverStateChanged));
  }
  // same for sender
}
```

2025-01-21 17:15 UTC, gavv requested changes

2025-01-21 17:15 UTC, gavv commented on lib/src/agent/android_backend.dart
> +      await refreshState(BackendEvent.statusCheckEvent.name);
1. "security" => "safety" (security is about protection from attacks, safety is about robust work)

2. "at any time while the application is running" - IMHO "at any time" is too vague. Why would refreshing state in this particular place ensures state correctness *at any time*? 

   I'd change it to something like this (feel free to rephrase). "Calls to connector may change service state. We want to refresh our cached state to ensure that the new state is visible to the caller immediately after return. Otherwise the caller may observe outdated state until we handle asynchronous event from connector".

2025-01-21 17:15 UTC, gavv commented on lib/src/agent/android_backend.dart
>    }
It's strange that `refreshState()` has event argument, especially given that it's mostly called when there is no actual event. Using artificial event like statusCheckEvent is also a bit confusing.

Maybe we can just remove eventCode argument, and move logging to onEvent and onError?

2025-01-21 17:34 UTC, gavv commented
CI fails because of a bug in a test.

```diff
diff --git a/test/model/sender_test.dart b/test/model/sender_test.dart
index 4d27c01..5946f8d 100644
--- a/test/model/sender_test.dart
+++ b/test/model/sender_test.dart
@@ -13,8 +13,8 @@ void main() {
   test('Check the senders initial values and getters.', () async {
     final sender = makeSender();
     expect(sender.isStarted, false);
-    expect(sender.sourcePort, -1);
-    expect(sender.repairPort, -1);
+    expect(sender.sourcePort, 10001);
+    expect(sender.repairPort, 10002);
     expect(sender.receiverIP, '');
     expect(
         sender.captureSource, CaptureSourceType.currentlyPlayingApplications);
```

Sender() constructor now initializes ports to 10001 and 10002, not -1.

Linux job is the only one which runs tests currently, hence only that job failed.

2025-02-07 11:10 UTC, Izchomatik commented on lib/src/agent/android_backend.dart
> +  final Event<Value<String>> stateChangeEvent = Event("stateChangeEvent");
Reworked

2025-02-07 11:10 UTC, Izchomatik commented on lib/src/agent/android_backend.dart
> +  bool senderIsAlive = false;
Reworked

2025-02-07 11:11 UTC, Izchomatik commented on lib/src/agent/android_backend.dart
> +      await refreshState(BackendEvent.statusCheckEvent.name);
Description updated

2025-02-07 11:13 UTC, Izchomatik commented on lib/src/agent/android_backend.dart
>    }
I thought about this in relation to other changes and decided not to remove this argument but to switch to an optional argument.

2025-02-07 11:13 UTC, Izchomatik commented
> CI fails because of a bug in a test.
> 
> ```diff
> diff --git a/test/model/sender_test.dart b/test/model/sender_test.dart
> index 4d27c01..5946f8d 100644
> --- a/test/model/sender_test.dart
> +++ b/test/model/sender_test.dart
> @@ -13,8 +13,8 @@ void main() {
>    test('Check the senders initial values and getters.', () async {
>      final sender = makeSender();
>      expect(sender.isStarted, false);
> -    expect(sender.sourcePort, -1);
> -    expect(sender.repairPort, -1);
> +    expect(sender.sourcePort, 10001);
> +    expect(sender.repairPort, 10002);
>      expect(sender.receiverIP, '');
>      expect(
>          sender.captureSource, CaptureSourceType.currentlyPlayingApplications);
> ```
> 
> Sender() constructor now initializes ports to 10001 and 10002, not -1.
> 
> Linux job is the only one which runs tests currently, hence only that job failed.

Test updated

2025-02-07 12:42 UTC, merged